package com.utec.model;
// default package
// Generated 13-jun-2019 9:48:43 by Hibernate Tools 5.2.3.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Byte codUsuario;
	private String nombre;
	private String clave;

	public Usuario() {
	}

	public Usuario(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public Byte getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(Byte codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

}
